Workspace/session7/7rd_session-homework/basic/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    # path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Workspace/session7/7rd_session-homework/main/urls.py
from django.urls import path, include
from .views import *

app_name = 'main'
urlpatterns = [
    # introduce page URL 연결하기 with 별명사용
    path('', showintroduce, name="showintroduce"),

    # activities page URL 연결하기 with 별명사용
    path('activities/', showactivities, name="showactivities"),

    # favorite page URL 연결하기 with 별명사용
    path('favorite/', showfavorite, name="showfavorite"),

    # contact page URL 연결하기 with 별명사용
    path('contact/', showcontact, name="showcontact"),

    path('<int:id>', detail, name='detail'),

    path('new/', new, name='new'),
    
    path('create/', create, name='create'),

    path('edit/<int:id>', edit, name='edit'),

    path('update/<int:id>', update, name='update'),

    path('delete/<int:id>', delete, name='delete'),

    path('<str:post_id>/create_comment', create_comment, name='create_comment'),
]

Workspace/session7/7rd_session-homework/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    path('mypage/', mypage, name='mypage'),
]

Workspace/session7/7rd_session-homework/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    acti_title = models.CharField(max_length=200)
    acti_date = models.CharField(max_length=100)
    acti_insert = models.TextField()
    acti_image = models.ImageField(upload_to = 'activities/', blank=True, null=True)

    def __str__(self):
        return self.acti_title


class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post ,on_delete=models.CASCADE, related_name ='comments')
    created_at = models.DateTimeField(auto_now=True)
    update_at = models.DateTimeField(auto_now=True)

Workspace/session7/7rd_session-homework/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

Workspace/session7/7rd_session-homework/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment

# introduce view 함수
def showintroduce(request):
    info = Post.objects.all()
    return render(request, 'main/introduce.html')

# activities view 함수
def showactivities(request):
    activities = Post.objects.all()
    return render(request, 'main/activities.html', {'activities':activities})

# contact view 함수
def showfavorite(request):
    return render(request, 'main/favorite.html')

# contact view 함수
def showcontact(request):
    contact = Post.objects.all()
    return render(request, 'main/contact.html')


def detail(request, id):
    post = get_object_or_404(Post, pk = id)
    all_comments = post.comments.all().order_by('-created_at')
    return render(request, 'main/detail.html', {'post':post, 'comments':all_comments})

def new(request):
    return render(request, 'main/new.html')

def create(request):
    new_acti = Post()
    new_acti.writer = request.user
    new_acti.acti_title = request.POST['acti_title']
    new_acti.acti_insert = request.POST['acti_insert']
    new_acti.acti_date = request.POST['acti_date']
    new_acti.acti_image = request.FILES.get('acti_image')
    new_acti.save()
    return redirect('main:detail', new_acti.id)

def edit(request, id):
    edit_acti = Post.objects.get(id=id)
    return render(request, 'main/edit.html', {'post':edit_acti})

def update(request, id):
    update_acti = Post.objects.get(id=id)
    update_acti.writer = request.user
    update_acti.acti_title = request.POST['acti_title']
    update_acti.acti_insert = request.POST['acti_insert']
    update_acti.acti_date = request.POST['acti_date']
    update_acti.save()
    return redirect('main:detail', update_acti.id)

def delete(request, id):
    delete_acti = Post.objects.get(id=id)
    delete_acti.delete()
    return redirect('main:showactivities')

def create_comment(request, post_id):
    new_comment = Comment()
    new_comment.writer = request.user
    new_comment.content = request.POST['content']
    new_comment.post = get_object_or_404(Post, pk = post_id)
    new_comment.save()
    return redirect('main:detail', post_id)

Workspace/session7/7rd_session-homework/users/views.py
from django.shortcuts import render
from main.models import Post
from django.contrib.auth.models import User
# Create your views here.

def mypage(request):
    user = request.user

    posts = Post.objects.filter(writer=user)
    return render(request, 'users/mypage.html', {'posts':posts})

Workspace/session7/7rd_session-homework/main/templates/main/activities.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="header">
            <h1 class="Hi">PYW's Activities</h1>
            <h2>💁‍♂️</h2>
        </div>
    </div>

    <main>
    
        <div class="container px-4" id="featured-3">
            <div class="b-example-divider"></div>
        
            <div class="contain px-4 py-5" id="hanging-icons">
                <h2 class="pb-2 border-bottom">Activities</h2>
                <p><br>
                    2017.03 ~ 2018.06 &nbsp;&nbsp;&nbsp;&nbsp;동국대학교 산업시스템공학과 과대표<br><br>
                    2017.03 ~ 2018.06 &nbsp;&nbsp;&nbsp;&nbsp;동국대학교 백상응원단 41기<br><br>
                    2017.11 ~ 2022.12 &nbsp;&nbsp;&nbsp;&nbsp; 동국대학교 공과대학 다빈치 프로그램 5기<br><br>
                    2018.03 ~ 2021.12 &nbsp;&nbsp;&nbsp;&nbsp;동국대학교 참사람봉사단 10기, 15-16기<br><br>
                    2018.09 ~ 2020.04 &nbsp;&nbsp;&nbsp;&nbsp;육군 병장 만기전역<br><br>
                    2020.08 ~ 2020.12 &nbsp;&nbsp;&nbsp;&nbsp;동국대학교 LINC+ 창의문제해결프로젝트<br><br>
                    2021.01 ~ 2021.01 &nbsp;&nbsp;&nbsp;&nbsp;한국장학재단 대학생 재능봉사캠프<br><br>
                    2021.01 ~ 2021.12 &nbsp;&nbsp;&nbsp;&nbsp;동국대학교 산업시스템공학과 제55대 학생회장<br><br>
                    2021.04 ~ 2021.11 &nbsp;&nbsp;&nbsp;&nbsp;과학기술정보통신부 프로보노 ICT 공모전<br><br>
                    2021.04 ~ 2021.11 &nbsp;&nbsp;&nbsp;&nbsp;한국중앙자원봉사센터 청년주도형 안녕캠페인 공모사업<br><br>
                    2021.06 ~ 2021.12 &nbsp;&nbsp;&nbsp;&nbsp;동국대학교 시스템안전연구실 학부연구생<br><br>
                    2022.01 ~ 2022.02 &nbsp;&nbsp;&nbsp;&nbsp;이트너스(주) 기업부설연구소 Platform Leader팀 인턴<br><br>
                    2022.03 ~ 2022.12 &nbsp;&nbsp;&nbsp;&nbsp;멋쟁이 사자처럼 10기<br><br>
                    
                    {% for activity in activities %}
                    {{activity.acti_date}} &nbsp;&nbsp;&nbsp;&nbsp;{{activity.acti_insert}}<br><br><img src="{{post.acti_image.url}}" alt="사진" height="10px"> <br><br>
                    {% endfor %}
                    <a href="{%url 'main:new'%}">추가하기</a>
                </p>
            </div>

            <div class="b-example-divider"></div>
        </div>
    </main>
        
        
        
    
{% endblock %}

Workspace/session7/7rd_session-homework/main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="header">
            <h1 class="Hi">☎️ Contact Me ☎️</h1>
        </div>
    </div>

    <main>
        <h1 class="visually-hidden">Contact</h1>
    
        <div class="container px-4" id="featured-3">
            <h2 class="pb-2 border-bottom">Contact</h2>
            <div class="row g-4 py-5 row-cols-lg-3">
                <div>
                    <h4>Phone : 010-9143-9799</h4>
                    <br>
                    <h4>E-mail : assayw119@naver.com</h4>
                    <div>
                        <br>
                        <h4>Instagram : 
                            <a href="https://www.instagram.com/y_woong__/" target="_blank" class="instagram">
                                <img src="{% static 'image/insta.jpeg' %}" width="50" height="50">
                            </a>
                        </h4>
                        <br>
                        <h4>Naver Blog :
                            <a href="https://blog.naver.com/assayw119" target="_blank" class="instagram">
                                <img src="{% static 'image/naver.png' %}" width="50" height="50">
                            </a>
                        </h4>
                        <br>
                        <h4>Tistory Blog :
                            <a href="https://heroeswillnotdie.tistory.com/" target="_blank" class="instagram">
                                <img src="{% static 'image/tistory.png' %}" width="50" height="50">
                            </a>
                        </h4>
                        <br>
                        <h4>Github :
                            <a href="https://github.com/assayw119" target="_blank" class="instagram">
                                <img src="{% static 'image/github.jpeg' %}" width="50" height="50">
                            </a>
                        </h4>
                    </div>
                </div>
                <div class="contact">
                    <div class="contact_image">
                        <img src="{% static 'image/profile2.png' %}">
                    </div>
                </div>

            </div>

            <div class="b-example-divider"></div>
    </main>
        
                
{% endblock %}

Workspace/session7/7rd_session-homework/main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{post.acti_title}}</h1>
{% if post.writer %}
    {% if 'user' in post.writer.username %}
        <h3>작성자 : {{ post.writer.last_name }}
        {{ post.writer.first_name }}</h3>
    {% else %}
        <h3>작성자 : {{ post.writer }}</h3>
    {% endif %}
{% else %}
    <h3>작성자 : 알 수 없음</h3>
{% endif %}
활동 날짜 : {{post.acti_date}}<br>
활동 내용 : {{post.acti_insert}}
<hr>
{%if post.acti_image %}
    <p><img src="{{ post.acti_image.url }}" alt='사진'></p>
{% endif %}

<div>
    <form action="{%url 'main:create_comment' post.id%}" method="POST">
        {%csrf_token%}
        <textarea name="content" placeholder="댓글내용입력"></textarea>
        <input type="submit" value="확인">
    </form>
</div>

<div>
    {% for comment in comments %}
        <div>
            작성자: {{comment.writer}}
            {{comment.content}}
            <br><hr>
        </div>
    {% endfor %}
</div>

<a href="{%url 'main:edit' post.id%}">수정하기</a>
<a href="{%url 'main:delete' post.id%}">삭제하기</a>
<a href="{%url 'main:showactivities'%}">돌아가기</a>
{% endblock %}

Workspace/session7/7rd_session-homework/main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <h1>글 수정하기</h1>
    <form action="{%url 'main:update' post.id %}" method="post">
        {%csrf_token%}
        <p>활동 제목: <input type="text" name="acti_title" value="{{post.acti_title}}"></p>
        <p>활동 날짜: <input type="text" name="acti_date" value="{{post.acti_date}}"></p>
        <p>활동 내용: <textarea type="text" name="acti_insert" id="" cols="30" rows="10">{{post.acti_insert}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</div>

{% endblock %}

Workspace/session7/7rd_session-homework/main/templates/main/favorite.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="header">
            <h1 class="Hi">PYW's Favorite</h1>
            <h2>💁‍♂️</h2>
        </div>
    </div>

    <main>
        <h1 class="visually-hidden">Favorite</h1>
    
        <div class="container px-4" id="featured-3">
            <h2 class="pb-2 border-bottom">Favorite</h2>
            <div class="row g-4 py-5 row-cols-lg-3">
                <div class="favorite">
                    <div class="favorite_image">
                        <h3 class="favorite_name">1. Activity</h3>
                        <img src="{% static 'image/activity.JPG' %}">
                    </div>
                </div>
                <div class="favorite">
                    <div class="favorite_image">
                        <h3 class="favorite_name">2. Band</h3>
                        <img src="{% static 'image/guitar.JPG' %}">
                    </div>
                </div>
                <div class="favorite">
                    <div class="favorite_image">
                        <h3 class="favorite_name">3. Exercise</h3>
                        <img src="{% static 'image/exercise.jpeg' %}">
                    </div>
                </div>
                <div class="favorite">
                    <div class="favorite_image">
                        <br><br>
                        <h3 class="favorite_name">4. Trable</h3>
                        <img src="{% static 'image/profile4.JPG' %}">
                    </div>
                </div>
                <div class="favorite">
                    <div class="favorite_image">
                        <br><br>
                        <h3 class="favorite_name">5. Competition</h3>
                        <img src="{% static 'image/expo.jpeg' %}">
                    </div>
                </div>
                <div class="favorite">
                    <div class="favorite_image">
                        <br><br>
                        <h3 class="favorite_name">6. Volunteer</h3>
                        <img src="{% static 'image/volunteer.JPG' %}">
                    </div>
                </div>
            </div>
        </div>
    
    </main>
        
{% endblock %}

Workspace/session7/7rd_session-homework/main/templates/main/introduce.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="header">
            <h1 class="intro">안녕하세요, 박영웅입니다.</h1>
        </div>
    </div>

    <main>
        <h1 class="visually-hidden">Profile</h1>
    
        <div class="container px-4" id="featured-3">
            <h2 class="pb-2 border-bottom">Profile</h2>
            <div class="row g-4 py-5 row-cols-lg-3">
                <div class="profile col">
                    <div class="profile_image">
                        <img src="{% static 'image/profile.jpg' %}">
                    </div>
                </div>
                <div class="profile_info">
                    <div>
                        <h2>박 영 웅 (朴英雄)</h2>
                        <h5>PARK YOUNG WOONG</h5>
                        <p>1998. 03. 05
                        <br>ESFJ</p>
                    </div>
                    <div>
                        <p>광명북고등학교 졸업</p>
                        <p>동국대학교 산업시스템공학과 17학번</p>
                        <p>데이터사이언스 소프트웨어 연계전공</p>
                        <p>4학년 1학기 재학</p>
                    </div>
                </div>
            </div>
        <div class="b-example-divider"></div>
    </main>
            
{% endblock %}

Workspace/session7/7rd_session-homework/main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{%url 'main:create' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <p>활동 제목 : <input type="text" name="acti_title"></p>
    <p>활동 날짜 : <input type="text" name="acti_date"></p>
    <p>활동 사진 : <input type="file" name="acti_image"></p>
    <p>활동 내용 : <textarea type="text" name="acti_insert" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>

</form>    
{% endblock %}

Workspace/session7/7rd_session-homework/main/templates/main/posts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
    <br>
    <h1>활동 목록</h1>

    <div>
        {% for post in posts %}
        <div>
            <h3>{{post.acti_title}}</h3>
            {% if post.writer %}
                {% if 'user' in post.writer.username %}
                    <h3>작성자 : {{ post.writer.last_name }} {{ post.writer.first_name }}</h3>
                {% else %}
                    <h3>작성자 : {{ post.writer }}</h3>
                {% endif %}
            {% else %}
                <h3>작성자 : 알 수 없음</h3>
            {% endif %}
            {{post.acti_date}}<br>
            {{post.acti_insert}}<br>
        </div>
        {% endfor %}
    </div>

    {% else %}
    <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
    <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
    {% endif %}

{% endblock %}